version: '3.3'

services:
  wanderlusterapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - mysql1
      - mysql2
      - mysql3
    ports:
      - "80:80"
    links:
      - redis:redis
      - mysql1:mysql1
      - mysql2:mysql2
      - mysql3:mysql3
    volumes:
      - ./:/var/www/wanderluster
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql1:
    image: mysql:8.0
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 237Ml1X8370D5nQ
      MYSQL_USER: wanderluster_api
      MYSQL_PASSWORD: P81Rp51UwxhCkvE
      MYSQL_DATABASE: P81Rp51UwxhCkvE
    volumes:
      - db1_data:/var/lib/mysql
  mysql2:
    image: mysql:8.0
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 237Ml1X8370D5nQ
      MYSQL_USER: wanderluster_api
      MYSQL_PASSWORD: P81Rp51UwxhCkvE
      MYSQL_DATABASE: P81Rp51UwxhCkvE
    volumes:
      - db2_data:/var/lib/mysql
  mysql3:
    image: mysql:8.0
    ports:
    - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 237Ml1X8370D5nQ
      MYSQL_USER: wanderluster_api
      MYSQL_PASSWORD: P81Rp51UwxhCkvE
      MYSQL_DATABASE: P81Rp51UwxhCkvE
    volumes:
    - db3_data:/var/lib/mysql
volumes:
  db1_data: {}
  db2_data: {}
  db3_data: {}