version: '3.3'

services:
  wanderlusterapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
    - redis
    - mysql
    ports:
    - "80:80"
    links:
    - redis:redis
    - mysql:mysql
    volumes:
    - ./:/var/www/wanderluster
  redis:
    image: redis
    ports:
    - "6379:6379"
  mysql:
    image: mysql:8.0
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 237Ml1X8370D5nQ
      MYSQL_USER: wanderluster_api
      MYSQL_PASSWORD: P81Rp51UwxhCkvE
      MYSQL_DATABASE: P81Rp51UwxhCkvE