version: '3.3'

services:
  wanderlusterapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - couchdb
    ports:
      - "80:80"
    links:
      - redis:redis
      - couchdb:couchdb
    volumes:
      - ./:/var/www/wanderluster
  redis:
    # port = 6379
    image: redis:6.0
  couchdb:
    # port = 5984
    image: couchdb:3.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: passpass