version: '3.3'

services:
  wanderlusterapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - couchdb
      - proxysql
    ports:
      - "80:80"
    links:
      - redis:redis
      - couchdb:couchdb
      - proxysql:proxysql
    volumes:
      - ./:/var/www/wanderluster
  proxysql:
    # ports = 6032, 6033
    image: proxysql/proxysql:2.0.9
    depends_on:
      - mysql1
      - mysql2
      - mysql3
      - mysql4
    links:
      - mysql1:mysql1
      - mysql2:mysql2
      - mysql3:mysql3
      - mysql3:mysql4
    volumes:
      - type: bind
        source: ./build/proxysql/proxysql.cnf
        target: /etc/proxysql.cnf
  redis:
    # port = 6379
    image: redis:6.0
  couchdb:
    # port = 5984
    image: couchdb:3.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: passpass
  mysql1:
    # port = 3306
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passpass
  mysql2:
    # port = 3306
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passpass
  mysql3:
    # port = 3306
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passpass
  mysql4:
    # port = 3306
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passpass