services:
  test.serializer:
    alias: 'App\DataModel\Serializer\Serializer'
    public: true
  test.file_adapter:
    alias: 'App\FileStorage\FileAdapters\ChainFileAdapter'
    public: true
  test.entity_manager:
    alias: 'App\Persistence\EntityManager'
    public: true
  test.attribute_manager:
    alias: 'App\Persistence\AttributeManager'
    public: true
  test.couch_db.client:
    alias: 'App\Persistence\CouchDB\Client'
    public: true
  test.http_client_factory:
    alias: 'App\Http\HttpClientFactory'
    public: true
  test.couch_db.client_factory:
    alias: 'App\Persistence\CouchDB\ClientFactory'
    public: true